version: '3.8'

services:
  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate
    restart: unless-stopped
    volumes:
      - ./data:/root/.dbgate
    networks:
      - proxy

networks:
  proxy:
    external: true
