version: '3.8'

services:
  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate
    restart: unless-stopped
    environment:
      BASIC_AUTH: "true"
      LOGIN: ${DBGATE_USER}
      PASSWORD: ${DBGATE_PASSWORD}
    volumes:
      - ./data:/root/.dbgate
    networks:
      - proxy

networks:
  proxy:
    external: true
